[package]
name = "enigma-cli"
version = "0.1.0"
edition = "2024"

description = "CLI demo for the enigma-core library"
license = "MIT"
repository = "https://github.com/umpire274/enigma"

[dependencies]
enigma-core = { path = "../enigma-core" }
clap = { version = "4.5", features = ["derive"] }
